// Emergency fallback, used only when the Google Sheet cannot be reached.
// A deliberately small, readable subset: every category, both stability levels,
// 4E fittings, plated and unplated, cheap and dear. Plain CSV on purpose so that
// damage in transit is obvious rather than silent. /status reports shoeCount.
export const FALLBACK_ROWS = 35;
export default `brand,model,category,stability,cushioning,stack_heel_mm,drop_mm,weight_g,widths,toebox,plate,best_for,heavier_runner_ok,beginner_friendly,durability,rrp_gbp,retailer,retailer_url,one_liner,status
Under Armour,Velociti Pace,daily_trainer,neutral,balanced,34,8,249,standard,medium,none,easy_miles;first_shoe;walking;gym,yes,yes,medium,100,SportsShoes,https://www.sportsshoes.com/product/und9687/,"Light, simple and keenly priced, a solid choice for regular training runs.",current
Adidas,Ultraboost 5,daily_trainer,neutral,plush,36,10,294,standard,medium,none,easy_miles;long_run;comfort;first_shoe;walking,yes,yes,high,160,SportsShoes,https://www.sportsshoes.com/store/adidas,Comfy and hard wearing but heavy. Better for walking and gentle jogs than training.,current
Brooks,Launch 12,daily_trainer,neutral,firm,33,8,249,standard,medium,none,easy_miles;first_shoe;gym,no,yes,medium,110,SportsShoes,https://www.sportsshoes.com/product/bro3520/,"The cheapest sensible Brooks. Firmer and lighter, and fine for a first pair.",current
Puma,Velocity Nitro 5,daily_trainer,neutral,balanced,33,8,244,standard,medium,none,easy_miles;first_shoe;walking;gym,yes,yes,high,110,SportsShoes,https://www.sportsshoes.com/product/pum3144/,Brilliant value all rounder that does easy runs and faster days without fuss.,current
Topo Athletic,Magnifly 6,daily_trainer,neutral,firm,26,0,255,standard,wide,none,easy_miles;gym,no,no,medium,125,SportsShoes,https://www.sportsshoes.com/product/top46/,"Flat, low and close to the ground with plenty of room for your toes.",current
Nike,Pegasus 42,daily_trainer,neutral,balanced,37,10,286,narrow;standard;wide,medium,none,easy_miles;long_run;first_shoe;walking;gym,yes,yes,high,129.99,SportsShoes,https://www.sportsshoes.com/product/nik25743/,"The safe all rounder. Handles daily runs, treadmill sessions and the odd parkrun without fuss.",current
Altra,Experience Flow 3,daily_trainer,neutral,balanced,32,4,255,standard,wide,none,easy_miles;first_shoe;walking;gym,yes,yes,medium,130,SportsShoes,https://www.sportsshoes.com/product/alt1012/,"Wide toe room with a small heel lift, the friendliest way into Altra.",current
Nike,Vomero 18,max_cushion,neutral,plush,46,10,298,narrow;standard;wide;extra_wide,medium,none,easy_miles;long_run;comfort;first_shoe;walking,yes,yes,high,134.99,SportsShoes,https://www.sportsshoes.com/product/nik25706/,"Thick, soft and forgiving underfoot. Great value if you want maximum comfort on easy runs.",current
New Balance,FuelCell SuperComp Trainer v3,max_cushion,neutral,plush,40,6,271,standard,medium,carbon,easy_miles;long_run;comfort;speed_work;race_day,yes,no,medium,210,SportsShoes,https://www.sportsshoes.com/product/new696302/,"A plated, super cushioned trainer for marathon build ups. Soft with a forward roll.",current
Brooks,Ghost Max 4,max_cushion,mild_support,plush,39,6,292,standard;wide,medium,none,easy_miles;long_run;comfort;first_shoe;walking,yes,yes,high,145,SportsShoes,https://www.sportsshoes.com/product/bro3654/,"A big, wide, forgiving platform. Very stable underfoot and kind to sore joints.",current
Under Armour,Velociti Distance,max_cushion,mild_support,plush,38,6,297,standard,medium,none,easy_miles;long_run;comfort;first_shoe;walking,yes,yes,medium,145,SportsShoes,https://www.sportsshoes.com/product/und9690/,"Cushioned and steady, built for slow long runs rather than anything quick.",current
Adidas,Supernova Prima 3,max_cushion,neutral,plush,40,6,275,standard,medium,none,easy_miles;long_run;comfort;first_shoe;walking;gym,yes,yes,medium,149.99,SportsShoes,https://www.sportsshoes.com/product/adi19066/,"Adidas' softest everyday cushion. Made for slow, comfortable miles rather than speed.",current
Topo Athletic,Atmos 2,max_cushion,neutral,plush,40,5,272,standard,wide,none,easy_miles;long_run;comfort;first_shoe;walking;gym,yes,yes,medium,155,SportsShoes,https://www.sportsshoes.com/product/top35/,"Very soft and roomy up front, a rare mix of max cushion and toe space.",current
Adidas,Supernova Solution 3,stability,stability,plush,35,8,281,standard,wide,none,easy_miles;comfort;first_shoe;walking;gym,yes,yes,medium,129.99,SportsShoes,https://www.sportsshoes.com/product/adi18330/,Cushioned support with a generous fit. Quietly keeps your foot tracking straight.,current
Asics,Gel-Kayano 33,stability,stability,plush,40,8,298,narrow;standard;wide;extra_wide,medium,none,easy_miles;long_run;comfort;walking,yes,yes,high,179.99,SportsShoes,https://www.sportsshoes.com/product/asi16582/,"The classic support shoe. Plush, stable and very hard to fall out with.",current
Nike,Structure 26,stability,stability,balanced,37,10,296,standard;wide;extra_wide,medium,none,easy_miles;long_run;first_shoe;walking,yes,yes,high,134.99,SportsShoes,https://www.sportsshoes.com/product/nik25774/,Steady and supportive if your ankles roll inwards. Built to last a lot of miles.,current
Topo Athletic,Ultrafly 6,stability,mild_support,balanced,32,5,272,standard,wide,none,easy_miles;first_shoe;walking;gym,yes,yes,medium,135,SportsShoes,https://www.sportsshoes.com/product/top53/,"Gentle support with a wide front end, handy if your feet need space.",current
Hoka,Arahi 9,stability,mild_support,balanced,37,8,284,standard;wide,medium,none,easy_miles;long_run;first_shoe;walking;gym,yes,yes,medium,140,SportsShoes,https://www.sportsshoes.com/product/hok3611/,"Gentle support built in without feeling stiff. A light, friendly stability shoe.",current
Saucony,Guide 19,stability,mild_support,balanced,37,6,280,standard;wide,medium,none,easy_miles;long_run;first_shoe;walking;gym,yes,yes,high,140,SportsShoes,https://www.sportsshoes.com/product/sau5603/,Quiet support that most people never notice. A good first stability shoe.,current
On,Cloudrunner 3,stability,mild_support,balanced,31,8,311,standard;wide,medium,none,easy_miles;first_shoe;walking,yes,yes,high,140,SportsShoes,https://www.sportsshoes.com/product/onr867/,"Steady, supportive and forgiving, a safe first proper running shoe for most people.",current
Adidas,Adizero Evo SL,tempo,neutral,balanced,36,6,224,standard;wide,medium,none,easy_miles;long_run;speed_work,yes,no,medium,129.99,SportsShoes,https://www.sportsshoes.com/product/adi19445/,"Light, springy and great value. A favourite for faster runs and shorter races.",current
Asics,Superblast 3,tempo,neutral,plush,46,8,235,standard,medium,none,easy_miles;long_run;speed_work,yes,no,high,199.99,SportsShoes,https://www.sportsshoes.com/product/asi16580/,"Tall, light and lively. Expensive, but it can do almost every type of run.",current
Hoka,Mach 7,tempo,neutral,balanced,37,5,237,standard;wide,medium,none,easy_miles;long_run;speed_work,no,no,medium,140,SportsShoes,https://www.sportsshoes.com/product/hok3624/,Light and springy without being a race shoe. Good for picking up the pace.,current
New Balance,FuelCell Rebel v5,tempo,neutral,balanced,33,6,223,standard;wide;extra_wide,wide,none,easy_miles;speed_work,no,no,medium,140,SportsShoes,https://www.sportsshoes.com/product/new696868/,"Light, bouncy and fun without a plate. A favourite for faster training runs.",current
Puma,Deviate Nitro 4,tempo,neutral,balanced,38,8,250,standard,medium,carbon,easy_miles;long_run;speed_work;race_day,yes,no,high,150,SportsShoes,https://www.sportsshoes.com/product/pum2928/,"One shoe that handles long runs, faster sessions and a half marathon happily.",current
Adidas,Adizero Adios Pro 4,race,neutral,balanced,39,6,200,standard;wide,narrow,carbon,speed_work;race_day,no,no,medium,219.99,SportsShoes,https://www.sportsshoes.com/product/adi19062/,"Adidas' top marathon racer. Very light, very fast and fits on the narrow side.",current
Nike,Alphafly 3,race,neutral,plush,40,8,210,standard,medium,carbon,speed_work;race_day,yes,no,medium,284.99,SportsShoes,https://www.sportsshoes.com/product/nik25687/,Nike's flagship marathon shoe. Springy air pods and a carbon plate for one big effort.,current
New Balance,FuelCell SuperComp Elite v6,race,neutral,plush,40,8,198,standard,medium,carbon,speed_work;race_day,no,no,low,230,SportsShoes,https://www.sportsshoes.com/product/new696739/,"New Balance's top marathon racer. Very light, very soft and built to go fast.",current
On,Cloudboom Strike 2,race,neutral,plush,40,4,191,standard,medium,carbon,speed_work;race_day,no,no,low,230,SportsShoes,https://www.sportsshoes.com/product/onr1002/,Very light carbon plated racer built for going fast on race day.,current
Asics,Gel-Trabuco 14,trail,mild_support,balanced,37,8,290,standard;wide,medium,none,trail;easy_miles;long_run,yes,yes,high,129.99,SportsShoes,https://www.sportsshoes.com/product/asi16622/,"A dependable everyday trail shoe. Good grip, decent cushioning and it lasts well.",current
Adidas,Terrex Agravic Speed Ultra 2,trail,neutral,balanced,38,6,250,standard,medium,none,trail;easy_miles;long_run,no,no,medium,199.99,SportsShoes,https://www.sportsshoes.com/product/adi18614/,Light and quick on the trails. Aimed at long off road races rather than beginners.,current
Hoka,Challenger 8,trail,neutral,balanced,40,8,287,standard;wide,medium,none,trail;easy_miles;long_run,yes,yes,high,130,SportsShoes,https://www.sportsshoes.com/product/hok3638/,"Half road shoe, half trail shoe. Ideal if your runs mix pavement and parks.",current
Altra,Lone Peak 9+,trail,neutral,balanced,25,0,327,standard;wide,wide,none,trail;easy_miles,yes,no,high,130,SportsShoes,https://www.sportsshoes.com/product/alt1050/,Cult trail shoe with masses of toe room and grippy Vibram rubber underneath.,current
Inov8,Mudtalon Speed v2,trail,neutral,firm,17,4,266,narrow;standard,medium,none,trail;easy_miles,no,no,medium,130,SportsShoes,https://www.sportsshoes.com/product/ino2607/,"Made for proper mud, cross country and fell races where grip beats comfort.",current
Nike,Pegasus Trail 5,trail,neutral,balanced,35,8,300,standard,wide,none,trail;easy_miles,yes,yes,medium,134.99,SportsShoes,https://www.sportsshoes.com/product/nik24888/,"A road shoe feel with proper grip. Good for towpaths, parks and light trails.",current
`;
